### ISSUE TITLE
Use case 1 is too broadly scoped by its headline

### ISSUE THREAD

**Issue by jan-ivar** [WICG/capture-handle#3]
_"Cross-app communication"_ is a means to an end, not a use case.

A descriptive headline of the use case presented would be: _“User drives a captured presentation app from a VC app”._

This is important for scope.

**Comment by lgrahl** [comment]
I don't want to open an issue just for that, so forgive the slight sidetrack but I think it fits well in here: Maybe explain the term _VC_ at least once. It took me quite a while. :wink:

**Comment by jan-ivar** [comment]
Thanks @lgrahl, I've updated the PR https://github.com/WICG/capture-handle/pull/7.

**Comment by alvestrand** [comment]
This comment is fine as a proposed clarification, but I don't see this as a reasonable issue to raise as a blocker for adoption.

**Comment by eladalon1983** [comment]
Please see the discussion's conclusion [here](https://github.com/WICG/capture-handle/issues/4#issuecomment-1056858436).
