### ISSUE TITLE
track.getCaptureHandle() observes navigation even after capture ends

### ISSUE THREAD

**Issue by jan-ivar** [WICG/capture-handle#9]
The way [track.getCaptureHandle()](https://wicg.github.io/capture-handle/#dom-mediastreamtrack-getcapturehandle) appears defined, the application can [observe](https://wicg.github.io/capture-handle/#dfn-observable) the user's navigation in the other tab long after tab capture of it has ended.

This is a privacy issue and defies user expectations. Users can forcefully revoke screen capture today in all browsers through browser UX, and would expect this tracking to stop when the track [ends](https://w3c.github.io/mediacapture-main/getusermedia.html#track-ended).

**Comment by alvestrand** [comment]
This can be solved by adding "If the track is ended, return null" to the checks. I don't see a reason not to do that.

Again, this does not seem a reasonable concern for blocking adoption.

**Comment by jan-ivar** [comment]
That would be a reasonable solution, as long as we agree this is not a part of the intended design.

**Comment by eladalon1983** [comment]
I implicitly assumed that getCaptureHandle() should stop working after the capture stops. Thank you for bringing up the issue, that it should be mentioned explicitly **how** it "stops working."
* Harald suggests returning null. 
* For completeness - we could also return undefined.
* There is also the alternative of raising an exception.

I'll modify the document to return null.

**Comment by eladalon1983** [comment]
Done.
